put the cherry on top of multiple $KEYS_DIR variables

diff --git a/keys b/keys
--- a/keys
+++ b/keys
@@ -54,7 +54,7 @@ create() {
 update() {
 	open || { close; exit 1; }
 
-	pw=$(cat "/tmp/key_pw_$USER")
+	pw=$(cat "$database_pw")
 
 	touch "/tmp/keys_$USER.lock"
 	chmod 600 "/tmp/keys_$USER.lock"
@@ -64,7 +64,7 @@ update() {
 	cp "$KEYS_DIR"/key_database "$KEYS_DIR"/key_database.bkup
 
 	{		
-		scrypt enc --passphrase file:"/tmp/key_pw_$USER" --logN $N -r $r -p $p "$database" "$KEYS_DIR"/key_database >/dev/null 2>&1 && rm "$KEYS_DIR"/key_database.bkup
+		scrypt enc --passphrase file:"$database_pw" --logN $N -r $r -p $p "$database" "$KEYS_DIR"/key_database >/dev/null 2>&1 && rm "$KEYS_DIR"/key_database.bkup
 
 		cd "$KEYS_DIR"
 		git add key_database keys.config
@@ -84,9 +84,9 @@ changemasterkey() {
 
 	[[ "$newmasterkey" == "$newmasterkey2" ]] || { echo "the keys don't match"; exit 1; }
 
-	echo -n "$newmasterkey" > "/tmp/key_pw_$USER"
+	echo -n "$newmasterkey" > "$database_pw"
 
-	pw=$(cat "/tmp/key_pw_$USER")
+	pw=$(cat "$database_pw")
 
 	touch "/tmp/keys_$USER.lock"
 	chmod 600 "/tmp/keys_$USER.lock"
@@ -96,7 +96,7 @@ changemasterkey() {
 	cp "$KEYS_DIR"/key_database "$KEYS_DIR"/key_database.bkup
 
 	{		
-		scrypt enc --passphrase file:"/tmp/key_pw_$USER" --logN $N -r $r -p $p "$database" "$KEYS_DIR"/key_database >/dev/null 2>&1 && rm "$KEYS_DIR"/key_database.bkup
+		scrypt enc --passphrase file:"$database_pw" --logN $N -r $r -p $p "$database" "$KEYS_DIR"/key_database >/dev/null 2>&1 && rm "$KEYS_DIR"/key_database.bkup
 
 		cd "$KEYS_DIR"
 		git add key_database keys.config
@@ -123,10 +123,10 @@ open() {
 	touch "$database"
 	chmod 600 "$database"
 	
-	if test -e "/tmp/key_pw_$USER"; then
-		pw=$(cat "/tmp/key_pw_$USER");
-		scrypt dec --passphrase file:"/tmp/key_pw_$USER" "$KEYS_DIR"/key_database "$database" || { 
-			echo "failure"; rm "/tmp/key_pw_$USER"; rm "$database"; exit 1; 
+	if test -e "$database_pw"; then
+		pw=$(cat "$database_pw");
+		scrypt dec --passphrase file:"$database_pw" "$KEYS_DIR"/key_database "$database" || { 
+			echo "failure"; rm "$database_pw"; rm "$database"; exit 1; 
 		} 
 		return 0
 	fi
@@ -135,23 +135,23 @@ open() {
 		echo -n "type your password: "
 		read -s pw
 		echo "checking the key..."
-		touch "/tmp/key_pw_$USER"
-		chmod 600 "/tmp/key_pw_$USER"
-		echo -n "$pw" > "/tmp/key_pw_$USER"
+		touch "$database_pw"
+		chmod 600 "$database_pw"
+		echo -n "$pw" > "$database_pw"
 	else
-		touch "/tmp/key_pw_$USER"
-		chmod 600 "/tmp/key_pw_$USER"
-		echo -n "$(cat $1)" > "/tmp/key_pw_$USER"
+		touch "$database_pw"
+		chmod 600 "$database_pw"
+		echo -n "$(cat $1)" > "$database_pw"
 	fi
 
-	scrypt dec --passphrase file:"/tmp/key_pw_$USER" "$KEYS_DIR"/key_database "$database" || { 
-		echo "failure"; rm "/tmp/key_pw_$USER"; rm "$database"; exit 1; 
+	scrypt dec --passphrase file:"$database_pw" "$KEYS_DIR"/key_database "$database" || { 
+		echo "failure"; rm "$database_pw"; rm "$database"; exit 1; 
 	}
 }
 close() {
 	{ 
 		rm -f "$database"
-		rm -f "/tmp/key_pw_$USER"
+		rm -f "$database_pw"
 	} && return 0
 }
 list() {
@@ -301,10 +301,15 @@ unlock() {
 }
 
 dbid=$(echo "$KEYS_DIR" | cksum | cut -d" " -f 1)
-database="/tmp/key_database_$USER_$dbid"
+mkdir /tmp/keys_"$USER"_$dbid 2> /dev/null
+chmod 700 /tmp/keys_"$USER"_$dbid
+
+tmpdir=/tmp/keys_"$USER"_$dbid
+database="$tmpdir"/database
+database_pw="$tmpdir"/password
 
 test -s "$database" || close
-test -s "/tmp/key_pw_$USER" || close
+test -s "$database_pw" || close
 
 if test -z "$KEYS_DIR"; then
 	export KEYS_DIR="$HOME/.key_database"
