fixed multiuser vulnerability

diff --git a/keys b/keys
--- a/keys
+++ b/keys
@@ -15,11 +15,7 @@ new_master_key() {
 	
 	[[ "$newmasterkey" == "$newmasterkey2" ]] || { echo "the keys don't match"; exit 1; }
 
-	# possible MITM attack here, if someone creates $database_pw before user does
-	# TO DO: check if $database_pw is owned by user...
-
 	touch "$database_pw"
-	chmod 600 "$database_pw"
 	
 	echo -n "$newmasterkey" | b2sum | awk '{print $1}' > "$database_pw"
 
@@ -359,14 +355,20 @@ tmpdir=/tmp/keys_"$USER"_$dbid
 database="$tmpdir"/database
 database_pw="$tmpdir"/password
 
+idu=$(id -u)
+dirid=$(stat -c "%u" "$tmpdir")
+
+if ! [ "$dirid" == $idu ]; then
+	echo -e "\e[1;31mfatal error: possible MITM attack! check temporal files permissions in /tmp/\e[0m"
+	exit 1
+fi
+
 test -s "$database" || close
 test -s "$database_pw" || close
 
 if test -z "$KEYS_DIR"; then
 	export KEYS_DIR="$HOME/.key_database"
-else
-	# yes, this is probably dumb, but what option do i got?
-	
+else	
 	export KEYS_DIR=$(echo -n "$KEYS_DIR" | sed "s.~.$HOME.g")
 
 	if ! [[ "$KEYS_DIR" == /* ]]; then
